spring.application.name=projeto3

# URL de conex�o: altere "nome_do_seu_banco" para o nome do schema criado no MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/projeto3?useSSL=false&serverTimezone=UTC

# Credenciais de acesso
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configura��es do Hibernate / JPA
# "update" cria ou atualiza as tabelas automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
